apiVersion: v1
kind: Pod
metadata:
  name: nrlabs-resources-pod
spec:
  containers:
  - name: nrlabs-resources-pod
    image: nrlabs/node-cache
    imagePullPolicy: Never
    resources:
        requests:
            memory: "32Mi"
            cpu: "250m"
        limits:
            memory: "64Mi"
            cpu: "250m"
