apiVersion: v1
kind: Pod
metadata:
  name: nrlabs-liveness-cmd
spec:
  containers:
  - name: liveness-cmd
    image: nrlabs/node-cache
    imagePullPolicy: Never
    args:
    - /bin/sh
    - -c
    - touch /tmp/meme-available; sleep 30; rm -rf /tmp/meme-available; sleep 30
    livenessProbe:
      exec:
        command:
        - cat
        - /tmp/meme-available
      initialDelaySeconds: 5
      periodSeconds: 5
